blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.gg/X8ExzygDGf
    about: Ask questions and discuss with other ToCount community members 
  - name: Website
    url: https://openscilab.com/
    about: Check out our website for more information
